import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthCotext"; 
import MenuLateral from "@/app/components/MenuLatral"; // ajusta o caminho se precisar

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        <AuthProvider>
          {/* Menu fixo do lado esquerdo */}
          <MenuLateral />

          {/* Conteúdo principal com padding para não ficar embaixo do menu */}
          <main className="ml-64 flex-1 p-4">
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
